// THIS IS GENERATED BY generate_actions.mjs.  DO NOT MAKE CHANGES.

import { ACCOUNT_ACTIONS } from '../constants/action_types'

export function updateEosObj(eosObj) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_EOS_OBJ, data: eosObj });
  };
}

export function updateEosAccountStr(eosAccountStr) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_EOS_ACCOUNT_STR, data: eosAccountStr });
  };
}

export function updateEosAccountAuthorityStr(eosAccountAuthorityStr) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_EOS_ACCOUNT_AUTHORITY_STR, data: eosAccountAuthorityStr });
  };
}

export function updateEosAccountInfoObj(eosAccountInfoObj) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_EOS_ACCOUNT_INFO_OBJ, data: eosAccountInfoObj });
  };
}

export function updateEosBalanceAmt(eosBalanceAmt) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_EOS_BALANCE_AMT, data: eosBalanceAmt });
  };
}

export function updateScatterObj(scatterObj) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_SCATTER_OBJ, data: scatterObj });
  };
}

export function updateScatterEosObj(scatterEosObj) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_SCATTER_EOS_OBJ, data: scatterEosObj });
  };
}

export function updateScatterDetectionStr(scatterDetectionStr) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_SCATTER_DETECTION_STR, data: scatterDetectionStr });
  };
}

export function updateEmailAddressStr(emailAddressStr) {
  return (dispatch) => {
   dispatch({ type: ACCOUNT_ACTIONS.UPDATE_EMAIL_ADDRESS_STR, data: emailAddressStr });
  };
}

