// THIS IS GENERATED BY generate_actions.mjs.  DO NOT MAKE CHANGES.

import { CREATOR_ACTIONS } from '../constants/action_types'

export function updateCreatorCurrentNameStr(creatorCurrentNameStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_CURRENT_NAME_STR, data: creatorCurrentNameStr });
  };
}

export function updateCreatorCurrentDescriptionStr(creatorCurrentDescriptionStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_CURRENT_DESCRIPTION_STR, data: creatorCurrentDescriptionStr });
  };
}

export function updateCreatorCurrentBannerStr(creatorCurrentBannerStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_CURRENT_BANNER_STR, data: creatorCurrentBannerStr });
  };
}

export function updateCreatorCurrentImageStr(creatorCurrentImageStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_CURRENT_IMAGE_STR, data: creatorCurrentImageStr });
  };
}

export function updateCreatorNameStr(creatorNameStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_NAME_STR, data: creatorNameStr });
  };
}

export function updateCreatorDescriptionStr(creatorDescriptionStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_DESCRIPTION_STR, data: creatorDescriptionStr });
  };
}

export function updateCreatorBannerStr(creatorBannerStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_BANNER_STR, data: creatorBannerStr });
  };
}

export function updateCreatorImageStr(creatorImageStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_IMAGE_STR, data: creatorImageStr });
  };
}

export function updateCreatorPublicationTitleStr(creatorPublicationTitleStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_PUBLICATION_TITLE_STR, data: creatorPublicationTitleStr });
  };
}

export function updateCreatorPublicationDescriptionStr(creatorPublicationDescriptionStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_PUBLICATION_DESCRIPTION_STR, data: creatorPublicationDescriptionStr });
  };
}

export function updateCreatorPublicationUrlStr(creatorPublicationUrlStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_PUBLICATION_URL_STR, data: creatorPublicationUrlStr });
  };
}

export function updateCreatorPublicationImageStr(creatorPublicationImageStr) {
  return (dispatch) => {
   dispatch({ type: CREATOR_ACTIONS.UPDATE_CREATOR_PUBLICATION_IMAGE_STR, data: creatorPublicationImageStr });
  };
}

