// THIS IS GENERATED BY generate_actions.mjs.  DO NOT MAKE CHANGES.

import { PATREOS_ACTIONS } from '../constants/action_types'

export function updateBalanceAmt(balanceAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_BALANCE_AMT, data: balanceAmt });
  };
}

export function updateStakedBalanceAmt(stakedBalanceAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_STAKED_BALANCE_AMT, data: stakedBalanceAmt });
  };
}

export function updateTransferToAccountStr(transferToAccountStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_TRANSFER_TO_ACCOUNT_STR, data: transferToAccountStr });
  };
}

export function updateTransferAmt(transferAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_TRANSFER_AMT, data: transferAmt });
  };
}

export function updateStakeAmt(stakeAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_STAKE_AMT, data: stakeAmt });
  };
}

export function updateUnstakeAmt(unstakeAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_UNSTAKE_AMT, data: unstakeAmt });
  };
}

export function updateFollowAccountStr(followAccountStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_FOLLOW_ACCOUNT_STR, data: followAccountStr });
  };
}

export function updatePledgeTokenSymbolStr(pledgeTokenSymbolStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PLEDGE_TOKEN_SYMBOL_STR, data: pledgeTokenSymbolStr });
  };
}

export function updatePledgeTokenContractStr(pledgeTokenContractStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PLEDGE_TOKEN_CONTRACT_STR, data: pledgeTokenContractStr });
  };
}

export function updatePledgeToAccountStr(pledgeToAccountStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PLEDGE_TO_ACCOUNT_STR, data: pledgeToAccountStr });
  };
}

export function updatePledgeAmt(pledgeAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PLEDGE_AMT, data: pledgeAmt });
  };
}

export function updatePledgeCycleNum(pledgeCycleNum) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PLEDGE_CYCLE_NUM, data: pledgeCycleNum });
  };
}

export function updatePledgesReceivedArr(pledgesReceivedArr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PLEDGES_RECEIVED_ARR, data: pledgesReceivedArr });
  };
}

export function updatePledgesGivenArr(pledgesGivenArr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PLEDGES_GIVEN_ARR, data: pledgesGivenArr });
  };
}

