// THIS IS GENERATED BY generate_actions.mjs.  DO NOT MAKE CHANGES.

import { PATREOS_ACTIONS } from '../constants/action_types'

export function updateBalanceAmt(balanceAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_BALANCE_AMT, data: balanceAmt });
  };
}

export function updateStakedBalanceAmt(stakedBalanceAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_STAKED_BALANCE_AMT, data: stakedBalanceAmt });
  };
}

export function updateTransferToAccountStr(transferToAccountStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_TRANSFER_TO_ACCOUNT_STR, data: transferToAccountStr });
  };
}

export function updateTransferAmt(transferAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_TRANSFER_AMT, data: transferAmt });
  };
}

export function updateStakeAmt(stakeAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_STAKE_AMT, data: stakeAmt });
  };
}

export function updateUnstakeAmt(unstakeAmt) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_UNSTAKE_AMT, data: unstakeAmt });
  };
}

export function updateFollowAccountStr(followAccountStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_FOLLOW_ACCOUNT_STR, data: followAccountStr });
  };
}

export function updateCreatorNameStr(creatorNameStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_CREATOR_NAME_STR, data: creatorNameStr });
  };
}

export function updateCreatorDescriptionStr(creatorDescriptionStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_CREATOR_DESCRIPTION_STR, data: creatorDescriptionStr });
  };
}

export function updateCreatorBannerStr(creatorBannerStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_CREATOR_BANNER_STR, data: creatorBannerStr });
  };
}

export function updateCreatorImageStr(creatorImageStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_CREATOR_IMAGE_STR, data: creatorImageStr });
  };
}

export function updatePublicationTitleStr(publicationTitleStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PUBLICATION_TITLE_STR, data: publicationTitleStr });
  };
}

export function updatePublicationDescriptionStr(publicationDescriptionStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PUBLICATION_DESCRIPTION_STR, data: publicationDescriptionStr });
  };
}

export function updatePublicationUrlStr(publicationUrlStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PUBLICATION_URL_STR, data: publicationUrlStr });
  };
}

export function updatePublicationImageStr(publicationImageStr) {
  return (dispatch) => {
   dispatch({ type: PATREOS_ACTIONS.UPDATE_PUBLICATION_IMAGE_STR, data: publicationImageStr });
  };
}

