// THIS IS GENERATED BY generate_actions.mjs.  DO NOT MAKE CHANGES.

import { RECURRINGPAY_ACTIONS } from '../constants/action_types'

export function updateBalancesArr(balancesArr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_BALANCES_ARR, data: balancesArr });
  };
}

export function updateSubscribersArr(subscribersArr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIBERS_ARR, data: subscribersArr });
  };
}

export function updateSubscriptionsArr(subscriptionsArr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIPTIONS_ARR, data: subscriptionsArr });
  };
}

export function updateDepositAmt(depositAmt) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_DEPOSIT_AMT, data: depositAmt });
  };
}

export function updateWithdrawAmt(withdrawAmt) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_WITHDRAW_AMT, data: withdrawAmt });
  };
}

export function updateDepositTokenSymbolStr(depositTokenSymbolStr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_DEPOSIT_TOKEN_SYMBOL_STR, data: depositTokenSymbolStr });
  };
}

export function updateWithdrawTokenSymbolStr(withdrawTokenSymbolStr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_WITHDRAW_TOKEN_SYMBOL_STR, data: withdrawTokenSymbolStr });
  };
}

export function updateDepositTokenContractStr(depositTokenContractStr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_DEPOSIT_TOKEN_CONTRACT_STR, data: depositTokenContractStr });
  };
}

export function updateWithdrawTokenContractStr(withdrawTokenContractStr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_WITHDRAW_TOKEN_CONTRACT_STR, data: withdrawTokenContractStr });
  };
}

export function updateSubscribeToAccountStr(subscribeToAccountStr) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIBE_TO_ACCOUNT_STR, data: subscribeToAccountStr });
  };
}

export function updateSubscriptionAmt(subscriptionAmt) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIPTION_AMT, data: subscriptionAmt });
  };
}

export function updateSubscriptionCycleNum(subscriptionCycleNum) {
  return (dispatch) => {
   dispatch({ type: RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIPTION_CYCLE_NUM, data: subscriptionCycleNum });
  };
}

