import fs from 'fs';
import util from 'util';

function generate(actions) {
  var fileBuffer = '';

  fileBuffer += "// THIS IS GENERATED BY generate_reducers.mjs.  DO NOT MAKE CHANGES.\n\n";
  fileBuffer += "import { combineReducers } from 'redux';\n";
  for(var a of actions) {
    fileBuffer += util.format("import %sReducer from './%s';\n", a, a);
  }
  fileBuffer += "\n";
  fileBuffer += "const reducers = {\n";
  for(var a of actions) {
    fileBuffer += util.format("    %sReducer,\n", a);
  }
  fileBuffer += "};\n\n";
  fileBuffer += "const rootReducer = combineReducers(reducers);\n\n";
  fileBuffer += "export default rootReducer;";

  var currentPath = process.cwd();
  fs.writeFile(util.format('%s/reducers/index.js', currentPath), fileBuffer, function(err) {
      if(err) {
          return console.log(err);
      }

      console.log("File saved to %s/reducers/index.js", currentPath);
  });

}

var actionsArr = [
  "account",
  "debug",
  "patreos",
  "recurringpay"
];

generate(actionsArr);
