export const ACCOUNT_ACTIONS = {

  // Blockchain Data
  UPDATE_EOS_ACCOUNT_STR: 'UPDATE_EOS_ACCOUNT_STR',
  UPDATE_EOS_ACCOUNT_INFO_OBJ: 'UPDATE_EOS_ACCOUNT_INFO_OBJ',
  UPDATE_EOS_BALANCE_AMT: 'UPDATE_EOS_BALANCE_AMT',

  // User Data
  UPDATE_SCATTER_DETECTION_STR: 'UPDATE_SCATTER_DETECTION_STR',
  UPDATE_EMAIL_ADDRESS_STR: 'UPDATE_EMAIL_ADDRESS_STR'

};

export const DEBUG_ACTIONS = {

  // EOS
  UPDATE_DEBUG_EOS_ACCOUNT_STR: 'UPDATE_DEBUG_EOS_ACCOUNT_STR',
  UPDATE_DEBUG_EOS_ACCOUNT_INFO_OBJ: 'UPDATE_DEBUG_EOS_ACCOUNT_INFO_OBJ',
  UPDATE_DEBUG_EOS_BALANCE_AMT: 'UPDATE_DEBUG_EOS_BALANCE_AMT',

  // Patreos
  UPDATE_DEBUG_PATR_BALANCE_AMT: 'UPDATE_DEBUG_PATR_BALANCE_AMT',
  UPDATE_DEBUG_PLEDGES_RECEIVED_ARR: 'UPDATE_DEBUG_PLEDGES_RECEIVED_ARR',
  UPDATE_DEBUG_PLEDGES_GIVEN_ARR: 'UPDATE_DEBUG_PLEDGES_GIVEN_ARR',

  // Recurringpay
  UPDATE_DEBUG_BALANCES_ARR: 'UPDATE_DEBUG_BALANCES_ARR',
  UPDATE_DEBUG_SUBSCRIBERS_ARR: 'UPDATE_DEBUG_SUBSCRIBERS_ARR',
  UPDATE_DEBUG_SUBSCRIPTIONS_ARR: 'UPDATE_DEBUG_SUBSCRIPTIONS_ARR',

};

export const CREATOR_ACTIONS = {

  // User Data
  UPDATE_CREATOR_NAME_STR: 'UPDATE_CREATOR_NAME_STR',
  UPDATE_CREATOR_DESCRIPTION_STR: 'UPDATE_CREATOR_DESCRIPTION_STR',
  UPDATE_CREATOR_BANNER_STR: 'UPDATE_CREATOR_BANNER_STR',
  UPDATE_CREATOR_IMAGE_STR: 'UPDATE_CREATOR_IMAGE_STR',

  UPDATE_CREATOR_PUBLICATION_TITLE_STR: 'UPDATE_CREATOR_PUBLICATION_TITLE_STR',
  UPDATE_CREATOR_PUBLICATION_DESCRIPTION_STR: 'UPDATE_CREATOR_PUBLICATION_DESCRIPTION_STR',
  UPDATE_CREATOR_PUBLICATION_URL_STR: 'UPDATE_CREATOR_PUBLICATION_URL_STR',
  UPDATE_CREATOR_PUBLICATION_IMAGE_STR: 'UPDATE_CREATOR_PUBLICATION_IMAGE_STR',
};

export const PATREOS_ACTIONS = {

  // Blockchain Data
  UPDATE_BALANCE_AMT: 'UPDATE_BALANCE_AMT',
  UPDATE_STAKED_BALANCE_AMT: 'UPDATE_STAKED_BALANCE_AMT',

  // User Data
  UPDATE_TRANSFER_TO_ACCOUNT_STR: 'UPDATE_TRANSFER_TO_ACCOUNT_STR',
  UPDATE_TRANSFER_AMT: 'UPDATE_TRANSFER_AMT',
  UPDATE_STAKE_AMT: 'UPDATE_STAKE_AMT',
  UPDATE_UNSTAKE_AMT: 'UPDATE_UNSTAKE_AMT',
  UPDATE_FOLLOW_ACCOUNT_STR: 'UPDATE_FOLLOW_ACCOUNT_STR',

  UPDATE_CREATOR_NAME_STR: 'UPDATE_CREATOR_NAME_STR',
  UPDATE_CREATOR_DESCRIPTION_STR: 'UPDATE_CREATOR_DESCRIPTION_STR',
  UPDATE_CREATOR_BANNER_STR: 'UPDATE_CREATOR_BANNER_STR',
  UPDATE_CREATOR_IMAGE_STR: 'UPDATE_CREATOR_IMAGE_STR',

  UPDATE_PUBLICATION_TITLE_STR: 'UPDATE_PUBLICATION_TITLE_STR',
  UPDATE_PUBLICATION_DESCRIPTION_STR: 'UPDATE_PUBLICATION_DESCRIPTION_STR',
  UPDATE_PUBLICATION_URL_STR: 'UPDATE_PUBLICATION_URL_STR',
  UPDATE_PUBLICATION_IMAGE_STR: 'UPDATE_PUBLICATION_IMAGE_STR',

  UPDATE_PLEDGE_TOKEN_SYMBOL_STR: 'UPDATE_PLEDGE_TOKEN_SYMBOL_STR',
  UPDATE_PLEDGE_TOKEN_CONTRACT_STR: 'UPDATE_PLEDGE_TOKEN_CONTRACT_STR',
  UPDATE_PLEDGE_TO_ACCOUNT_STR: 'UPDATE_PLEDGE_TO_ACCOUNT_STR',
  UPDATE_PLEDGE_AMT: 'UPDATE_PLEDGE_AMT',
  UPDATE_PLEDGE_CYCLE_NUM: 'UPDATE_PLEDGE_CYCLE_NUM',

  UPDATE_PLEDGES_RECEIVED_ARR: 'UPDATE_PLEDGES_RECEIVED_ARR',
  UPDATE_PLEDGES_GIVEN_ARR: 'UPDATE_PLEDGES_GIVEN_ARR'

};

export const RECURRINGPAY_ACTIONS = {

  // Blockchain Data
  UPDATE_BALANCES_ARR: 'UPDATE_BALANCES_ARR',
  UPDATE_SUBSCRIBERS_ARR: 'UPDATE_SUBSCRIBERS_ARR',
  UPDATE_SUBSCRIPTIONS_ARR: 'UPDATE_SUBSCRIPTIONS_ARR',

  // User Data
  UPDATE_DEPOSIT_AMT: 'UPDATE_DEPOSIT_AMT',
  UPDATE_WITHDRAW_AMT: 'UPDATE_WITHDRAW_AMT',
  UPDATE_DEPOSIT_TOKEN_SYMBOL_STR: 'UPDATE_DEPOSIT_TOKEN_SYMBOL_STR',
  UPDATE_WITHDRAW_TOKEN_SYMBOL_STR: 'UPDATE_WITHDRAW_TOKEN_SYMBOL_STR',
  UPDATE_DEPOSIT_TOKEN_CONTRACT_STR: 'UPDATE_DEPOSIT_TOKEN_CONTRACT_STR',
  UPDATE_WITHDRAW_TOKEN_CONTRACT_STR: 'UPDATE_WITHDRAW_TOKEN_CONTRACT_STR',
  UPDATE_SUBSCRIBE_TO_ACCOUNT_STR: 'UPDATE_SUBSCRIBE_TO_ACCOUNT_STR',
  UPDATE_SUBSCRIPTION_AMT: 'UPDATE_SUBSCRIPTION_AMT',
  UPDATE_SUBSCRIPTION_CYCLE_NUM: 'UPDATE_SUBSCRIPTION_CYCLE_NUM'

};
