export const ACCOUNT_ACTIONS = {
  UPDATE_NAME: 'UPDATE_NAME',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  UPDATE_TRANSACTIONS: 'UPDATE_TRANSACTIONS',
  DETECT_SCATTER: 'DETECT_SCATTER',
  UPDATE_VAULT_INFO: 'UPDATE_VAULT_INFO',
  UPDATE_EOS_BALANCE: 'UPDATE_EOS_BALANCE',
  UPDATE_PATR_BALANCE: 'UPDATE_PATR_BALANCE'
};

export const PATREOS_TOKEN_ACTIONS = {
  UNSTAKED_BALANCE: 'UNSTAKED_BALANCE',
  STAKED_BALANCE: 'STAKED_BALANCE',
  RECEIVER_ACCOUNT: 'RECEIVER_ACCOUNT',
  QUANTITY_TO_TRANSFER: 'AMOUNT_TO_TRANSFER',
  QUANTITY_TO_STAKE: 'AMOUNT_TO_STAKE',
  QUANTITY_TO_UNSTAKE: 'AMOUNT_TO_UNSTAKE',
  QUANTITY_TO_PLEDGE: 'AMOUNT_TO_PLEDGE',
  PLEDGES: 'PLEDGES',
  PLEDGERS: 'PLEDGERS',
  PLEDGE_CYCLE_DAYS: 'PLEDGE_CYCLE_DAYS'
};
