export const UI_ACTIONS = {
  UPDATE_NAME: 'UPDATE_NAME',
  UPDATE_USER_INFO: 'UPDATE_USER_INFO',
  INCREMENT_COUNT: 'INCREMENT_COUNT',
  DETECT_SCATTER: 'DETECT_SCATTER'
};

export const TEST_ACTION = {
  ACTION_1: 'ACTION_1'
};
