// THIS IS GENERATED BY generate_reducers.mjs.  DO NOT MAKE CHANGES.

import { DEBUG_ACTIONS } from '../constants/action_types'

export default (
  state = {
    debugEosAccountStr: '',
    eosAccountInfoObj: {},
    eosBalanceAmt: '0.0000',
    patrBalanceAmt: '0.0000',
    pledgesReceivedArr: [],
    pledgesGivenArr: [],
    balancesArr: [],
    subscribersArr: [],
    subscriptionsArr: [],
  }, action) => {
  switch (action.type) {
  case DEBUG_ACTIONS.UPDATE_DEBUG_EOS_ACCOUNT_STR:
    return { ...state, debugEosAccountStr: action.data };
  case DEBUG_ACTIONS.UPDATE_EOS_ACCOUNT_INFO_OBJ:
    return { ...state, eosAccountInfoObj: action.data };
  case DEBUG_ACTIONS.UPDATE_EOS_BALANCE_AMT:
    return { ...state, eosBalanceAmt: action.data };
  case DEBUG_ACTIONS.UPDATE_PATR_BALANCE_AMT:
    return { ...state, patrBalanceAmt: action.data };
  case DEBUG_ACTIONS.UPDATE_PLEDGES_RECEIVED_ARR:
    return { ...state, pledgesReceivedArr: action.data };
  case DEBUG_ACTIONS.UPDATE_PLEDGES_GIVEN_ARR:
    return { ...state, pledgesGivenArr: action.data };
  case DEBUG_ACTIONS.UPDATE_BALANCES_ARR:
    return { ...state, balancesArr: action.data };
  case DEBUG_ACTIONS.UPDATE_SUBSCRIBERS_ARR:
    return { ...state, subscribersArr: action.data };
  case DEBUG_ACTIONS.UPDATE_SUBSCRIPTIONS_ARR:
    return { ...state, subscriptionsArr: action.data };
  default:
    return state;
  }
};
