// THIS IS GENERATED BY generate_reducers.mjs.  DO NOT MAKE CHANGES.

import { DEBUG_ACTIONS } from '../constants/action_types'

export default (
  state = {
    debugEosAccountStr: '',
    debugEosAccountInfoObj: {},
    debugEosBalanceAmt: '0.0000',
    debugPatrBalanceAmt: '0.0000',
    debugPledgesReceivedArr: [],
    debugPledgesGivenArr: [],
    debugBalancesArr: [],
    debugSubscribersArr: [],
    debugSubscriptionsArr: [],
  }, action) => {
  switch (action.type) {
  case DEBUG_ACTIONS.UPDATE_DEBUG_EOS_ACCOUNT_STR:
    return { ...state, debugEosAccountStr: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_EOS_ACCOUNT_INFO_OBJ:
    return { ...state, debugEosAccountInfoObj: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_EOS_BALANCE_AMT:
    return { ...state, debugEosBalanceAmt: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_PATR_BALANCE_AMT:
    return { ...state, debugPatrBalanceAmt: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_PLEDGES_RECEIVED_ARR:
    return { ...state, debugPledgesReceivedArr: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_PLEDGES_GIVEN_ARR:
    return { ...state, debugPledgesGivenArr: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_BALANCES_ARR:
    return { ...state, debugBalancesArr: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_SUBSCRIBERS_ARR:
    return { ...state, debugSubscribersArr: action.data };
  case DEBUG_ACTIONS.UPDATE_DEBUG_SUBSCRIPTIONS_ARR:
    return { ...state, debugSubscriptionsArr: action.data };
  default:
    return state;
  }
};
