// THIS IS GENERATED BY generate_reducers.mjs.  DO NOT MAKE CHANGES.

import { combineReducers } from 'redux';
import accountReducer from './account';
import creatorReducer from './creator';
import debugReducer from './debug';
import patreosReducer from './patreos';
import recurringpayReducer from './recurringpay';

const reducers = {
    accountReducer,
    creatorReducer,
    debugReducer,
    patreosReducer,
    recurringpayReducer,
};

const rootReducer = combineReducers(reducers);

export default rootReducer;