// THIS IS GENERATED BY generate_reducers.mjs.  DO NOT MAKE CHANGES.

import { RECURRINGPAY_ACTIONS } from '../constants/action_types'

export default (
  state = {
    balancesArr: [],
    subscribersArr: [],
    subscriptionsArr: [],
    depositAmt: '0.0000',
    withdrawAmt: '0.0000',
    depositTokenSymbolStr: '',
    withdrawTokenSymbolStr: '',
    depositTokenContractStr: '',
    withdrawTokenContractStr: '',
    subscribeToAccountStr: '',
    subscriptionAmt: '0.0000',
    subscriptionCycleNum: 0,
  }, action) => {
  switch (action.type) {
  case RECURRINGPAY_ACTIONS.UPDATE_BALANCES_ARR:
    return { ...state, balancesArr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIBERS_ARR:
    return { ...state, subscribersArr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIPTIONS_ARR:
    return { ...state, subscriptionsArr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_DEPOSIT_AMT:
    return { ...state, depositAmt: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_WITHDRAW_AMT:
    return { ...state, withdrawAmt: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_DEPOSIT_TOKEN_SYMBOL_STR:
    return { ...state, depositTokenSymbolStr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_WITHDRAW_TOKEN_SYMBOL_STR:
    return { ...state, withdrawTokenSymbolStr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_DEPOSIT_TOKEN_CONTRACT_STR:
    return { ...state, depositTokenContractStr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_WITHDRAW_TOKEN_CONTRACT_STR:
    return { ...state, withdrawTokenContractStr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIBE_TO_ACCOUNT_STR:
    return { ...state, subscribeToAccountStr: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIPTION_AMT:
    return { ...state, subscriptionAmt: action.data };
  case RECURRINGPAY_ACTIONS.UPDATE_SUBSCRIPTION_CYCLE_NUM:
    return { ...state, subscriptionCycleNum: action.data };
  default:
    return state;
  }
};
